### ISSUE TITLE
Frustrating interlinking between t1 and t2 docs

### ISSUE THREAD

**Issue by CarlQLange** [tessel/t1-docs#80]
I'd love it if all the t1 documentation lived here, including module documentation. I have an audio module for which there is apparently no documentation, because the t2 doesn't have the audio module?

**Comment by CarlQLange** [comment]
It's really frustrating that there are 4 dead links on this page alone https://github.com/tessel/t1-docs/blob/master/hardware-api.md to docs that are allegedly useful, but disappeared in the rush to get tessel.io ready for T2.

**Comment by Frijol** [comment]
Really sorry about that! My fault, I got overexcited about building the new docs :/

Documentation for each module is on its corresponding repo. These live in https://github.com/tessel and are all named with their npm package names, so Audio has docs at https://github.com/tessel/audio-vs1053b.

They can also be found on https://tessel.io/modules#module-audio - I usually use that as a directory, which is why I never noticed this problem.

Proposed fixes:

* [ ] Add all module documentation links to t1-docs repo readme
* [ ] Go through all docs pages and correct any dead links
